version: '2'
services:
  altodpsk1-app:
    image: altodpsk1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://altodpsk1-postgresql:5432/AltoDpsk1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  altodpsk1-postgresql:
    extends:
      file: postgresql.yml
      service: altodpsk1-postgresql
